"""Rename email_confirmed to is_confirmed

Revision ID: 857704b578d5
Revises: a26050980e19
Create Date: 2025-11-30 22:53:37.325213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857704b578d5'
down_revision = 'a26050980e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###
